### ISSUE TITLE
Question: Can indenting soft wrapped lines be disabled?

### ISSUE THREAD

**Issue by bobrocke** [atom/language-gfm#104]
Is there a way to disable soft wrapped indents for just the `.source .gfm` scope?

**Comment by izuzak** [comment]
@bobrocke Should be possible. Add this to your config.cson:

```
".gfm.source":
  editor:
    softWrapHangingIndent: 0
```

@benogle @kevinsawicki If we wanted to show this config option in the settings view for language packages, and not just in core settings, what would need to be changed? That config name (softWrapHangingIndent) is listed [here](https://github.com/atom/atom/blob/1e99a2154722886ff8bc1da79aea5715ebd9ccf5/src/config-schema.coffee) as both core and scoped, but shows up only under core settings for me. The same is true for some other config options which can be scoped.

![screen shot 2015-05-20 at 13 18 22](https://cloud.githubusercontent.com/assets/38924/7724551/c159c4de-fef2-11e4-90aa-cb5c1f0a67c2.png)

**Comment by bobrocke** [comment]
@izuzak Thanks, that works fine. But it would be nice to have that in the language settings.

**Comment by kevinsawicki** [comment]
> if we wanted to show this config option in the settings view for language packages, and not just in core settings, what would need to be changed

I think here: https://github.com/atom/settings-view/blob/1e1619c1719f2623bcd21a0297fcc16ee2baf1c7/lib/settings-panel.coffee#L14-L27
