### ISSUE TITLE
Bug detecting italic syntax

### ISSUE THREAD

**Issue by ptoomey3** [atom/language-gfm#105]
Most non-alphanumeric characters that proceed a * or _ cause the remaining MD to italicize. For example

```
test!_test
This is a test


test!*test
This is a test
```

The `!` can be replaced with most non-alphanumeric characters with the same result.

**Comment by izuzak** [comment]
Looks like a duplicate :bug: :bug: of https://github.com/atom/language-gfm/issues/44, gonna close this in favor of that issue.
