### ISSUE TITLE
Overzealous highlighting applied to embedded HTML attributes

### ISSUE THREAD

**Issue by Alhadis** [atom/language-gfm#108]
The image below says everything:

![figure-1](https://cloud.githubusercontent.com/assets/2346707/8024667/043f3460-0d7f-11e5-9a13-aaf40cad987d.png)

Since GitHub-flavoured markdown won't apply any extra formatting to the contents of embedded HTML blocks, the editor's highlighting behaviour should probably reflect this.

I also noticed the same discrepancy being applied to fenced-off GFM, too, so perhaps it's less a problem with the grammar package and more to do with [Linguist](https://github.com/github/linguist)? Should I be filing an issue there instead?
```markdown
### Embedded HTML

<p>**This shouldn't be bold, right?**</p>
<dl>
	<dt><a href="http://so.me/link" target="_blank">Definition term</a></dt>
	<dd>
		**Hey, wait a second, this shouldn't be in italic...**
	</dd>
</dl>
```

**Comment by 50Wliu** [comment]
Nope, you're on the right repository :smile:.
However, this has already been reported in #44, so please go subscribe there instead.

**Comment by Alhadis** [comment]
Sorry, my bad. :(
