### ISSUE TITLE
Feature wish: command to make it bold (or italic)

### ISSUE THREAD

**Issue by kgrossjo** [atom/language-gfm#113]
WIBNI there was a command that I could call via the palette or via a keybinding that made the selection bold?  (And another one that made it italic?)

Or maybe if something is selected and I type <kbd>*</kbd> then it could surround the selection, like <kbd>(</kbd> does today, and unlike today where it overtypes the selection.

**Comment by lee-dohm** [comment]
WIBNI?

**Comment by thomasjo** [comment]
> WIBNI?

"Wouldn't it be nice if".

**Comment by oraculus** [comment]
you could install the package **Markdown Writer** and add the following to your keymap file:
```
  "ctrl-i":       "markdown-writer:toggle-italic-text"
  "ctrl-b":       "markdown-writer:toggle-bold-text"
```

**Comment by uloco** [comment]
This should definitely behave like <kbd>(</kbd> or <kbd>`</kbd> and should make bold when inserted twice

**Comment by burodepeper** [comment]
I've added this behavior to `language-markdown` a while ago. With text selected, pressing `*` (<kbd>shift + 8</kbd>) or `_` (<kbd>shift + -</kbd>) marks the selection with strong or regular emphasis. Feel free to add it to `language-gfm`.

**Comment by LunarGem** [comment]
Has this already been done? I'd like to try if it's a simple thing (and if CoffeeScript isn't too different from JavaScript that it would negate all of my knowledge).

**Comment by 50Wliu** [comment]
This is now possible with the improved bracket-matcher settings.  Go to Settings -> Packages -> Bracket Matcher -> Autocomplete Characters, and add `, **, __` to the end of the list.

Result:
![gfm-asterisks](https://cloud.githubusercontent.com/assets/2766036/23804873/b601239e-0589-11e7-914d-1572904491e1.gif)
