### ISSUE TITLE
Make the language more modular

### ISSUE THREAD

**Issue by tpoisot** [atom/language-gfm#124]
There are a number of markdown / pandoc packages (such as `language-pfm` by @leipert), and I have been wondering about the opportunity of adopting a more modular structure.

For example, `language-markdown` would have something (close to) [CommonMark](http://commonmark.org/), and serve as a "basis". Then we could have something like `language-criticmark`, `language-markdowntable`, `language-markdownfencedblocks`, etc, for things that are likely to differ between GFM and other flavors of markdown.

The `language-gfm` and  `language-pfm` would then be wrapper around a number / all of these packages.

I know that it sounds like a pretty big redesign (it probably is), but it would make maintenance easier (since all of these packages would end up being smaller anyway).

Ideas? Opinions?

**Comment by leipert** [comment]
Yes. I am actually considering the following:

A configurable package which unites all the markdown flavors.
I already spoke with @burodepeper privately about it in Slack.

A simple solution would be:

Extend the Grammar Class like https://github.com/p-e-w/language-javascript-semantic does and load rules depending on the flavor the user did set in his settings. I am going to work on this this weekend.

I hope noone grabs the `language-markdown` package ;)

**Comment by burodepeper** [comment]
Yeah @leipert, let's try and set up a basic outline this weekend, and then we'll take it from there. I have nothing else planned, so with a bit of luck we can get a bunch of it done by just copy and pasting.

**Comment by tpoisot** [comment]
Cool. I'm happy to help. I think it's the type of project that would be useful, but need to engage people using the package. 
Wouldn't it be more beneficial to discuss this here rather than in a private slack channel?


Sent from a mobile device - pardon the brevity/typos.

-------- Message d'origine --------
De : David van Gemeren <notifications@github.com> 
Date : 09/02/2015  10:55 AM  (GMT-05:00) 
À : atom/language-gfm <language-gfm@noreply.github.com> 
Cc : Timothée Poisot <tim@poisotlab.io> 
Objet : Re: [language-gfm] Make the language more modular (#124) 

Yeah @leipert, let's try and set up a basic outline this weekend, and then we'll take it from there. I have nothing else planned, so with a bit of luck we can get a bunch of it done by just copy and pasting.

**Comment by burodepeper** [comment]
You are right!

I've just initiated the package, and I suggest that @leipert and I will set up some basics over the weekend. You are welcome to join us over at https://github.com/burodepeper/language-markdown to join in on the fun.

I think we can agree that CommonMark is a good point of origin, and that a way of extending basic Markdown is desirable. I guess we'll go from there. The current packages aren't perfect, but they do fine. So there's no hurry. I'm (we're?) just eager to get things started : )

**Comment by tpoisot** [comment]
Awesome! 

Do you then think that it is unnecessary to split some other parts of the grammar in additional packages? CriticaMarkup notably is not standard in markdown or commonmark, so maybe it is a good candidate for being moved?

**Comment by burodepeper** [comment]
I think that's an item we have to discuss.
Perhaps the package is merely an umbrella that allows other packages to extend it in some form. Or maybe it houses multiple flavors and leaves it up to the user to decide which ones to enable.
