### ISSUE TITLE
Kramdown and target="_blank"

### ISSUE THREAD

**Issue by johanson** [atom/language-gfm#126]
Since GitHub pages use Jekyll and Jekyll Kramdown, it might be relevant.

GFM thinks the italic tag is still opened, therefor everything that comes after is italic.

![kram](https://cloud.githubusercontent.com/assets/720806/10173648/0d5362e2-66ee-11e5-9de7-8bf85660e418.png)

**Comment by 50Wliu** [comment]
This looks like a duplicate of #44 - please subscribe there for updates.
