### ISSUE TITLE
Need help: About link style.

### ISSUE THREAD

**Issue by havthgem** [atom/language-gfm#139]
I don't like link has underline. How to remove it?
<img width="431" alt="Link has underline" src="https://cloud.githubusercontent.com/assets/11625453/13073183/3a6d465a-d4d8-11e5-9065-69eef82e9a97.png">

**Comment by lee-dohm** [comment]
This kind of question is generally best for [Discuss](https://discuss.atom.io), the official Atom and Electron message board. On Discuss there is a [FAQ category](https://discuss.atom.io/c/faq) where you'll find [this post](https://discuss.atom.io/t/how-do-i-determine-what-css-class-to-use-to-highlight-a-specific-syntax/23211). Once you have the CSS class determined, you can use standard CSS (following [this example](https://discuss.atom.io/t/im-trying-to-change-my-syntax-colors-from-styles-less-but-it-isnt-working/19388)) to remove the underline from the affected items.

Let us know if this doesn't cover your question!

**Comment by havthgem** [comment]
Thank you! Is helpful.
