### ISSUE TITLE
Rename to language-githubmarkdown

### ISSUE THREAD

**Issue by alexjurkiewicz** [atom/language-gfm#163]
I spent a few minutes looking for this package in my atom package list and getting puzzled because it didn't show up when searching for 'markdown'.

**Comment by thomasjo** [comment]
Technically the grammar is called _GitHub Flavored Markdown_, so it would have to be language-github-flavored-markdown (or at least language-github-markdown). Renaming this does not solve the underlying problem though (the fact that the local search does not search through the package keywords/tags), so I'm closing this as wontfix.

Unless there's already an open issue on the settings-view repo concerning search/filtering not supporting keywords, feel free to open an issue for that 🙇
