### ISSUE TITLE
Markdown syntax highlighting fails after ```

### ISSUE THREAD

**Issue by bitflop** [atom/language-gfm#165]
![shot](https://cloud.githubusercontent.com/assets/15728070/17455365/83460ee8-5bb5-11e6-9684-28fa75cb2a49.png)

It is reproducible every time.

**Comment by bitflop** [comment]
Removing the 'while' word from the text in ``` box solves the problem, so that's something to look into.

**Comment by 50Wliu** [comment]
This is because you're using Bash to highlight a code block that is distinctly **not** bash-syntax.  `while` is a reserved word in Bash.

**Comment by bitflop** [comment]
This is an error message thrown at the bash console by X, so it's bash in that sense, though not bash scripting. However, since this is going to be converted into HTML and highlighted using Prism, the bash tag is AFAIK the right one to use.
