### ISSUE TITLE
Kotlin Support

### ISSUE THREAD

**Issue by thomasnield** [atom/language-gfm#166]
Is it possible we can add [Kotlin](http://kotlinlang.org/) support for Markdown code samples? I'm currently getting no styling. 

![image](https://cloud.githubusercontent.com/assets/7420801/18220749/eebed458-713a-11e6-8c9b-a5b09fe3684c.png)

**Comment by radixdev** [comment]
@thomasnield https://github.com/atom/language-gfm/pull/236 😄

**Comment by radixdev** [comment]
@thomasnield I think we can close this now. The update is merged

**Comment by rsese** [comment]
Thanks @radixdev :bow:
