### ISSUE TITLE
Go formatting is broken for `golang` tags

### ISSUE THREAD

**Issue by jredville** [atom/language-gfm#168]
I think that the golang tag should work based on https://github.com/atom/language-gfm/blob/master/grammars/gfm.cson#L483, however:

    ```golang
    func AFunction() error {
      return nil
    }
    ```

```golang
func AFunction() error {
  return nil
}
```

does not work while:

    ```go
    func AFunction() error {
      return nil
    }
    ```

```go
func AFunction() error {
  return nil
}
```

works.

**Comment by 50Wliu** [comment]
This is only for Markdown support within Atom, not on GitHub.
