### ISSUE TITLE
Inline code in markdown preview fuzzy

### ISSUE THREAD

**Issue by cavaunpeu** [atom/language-gfm#179]
Block code works fine. Inline code looks fuzzy. Ideas? 

Thanks for a great package.

![screen shot 2016-12-21 at 11 22 11 am](https://cloud.githubusercontent.com/assets/7306239/21387571/197db69c-c770-11e6-8be5-1c5d62964ebf.png)

**Comment by 50Wliu** [comment]
This belongs on the [markdown-preview](https://github.com/atom/markdown-preview) package - can you please move it there?  Additionally, please supply what Atom version (`atom --version`) and OS you're using in the new issue.  Thanks :).
