### ISSUE TITLE
Fenced code block fails to end if block contains unparsable backtick

### ISSUE THREAD

**Issue by droberts-ada** [atom/language-gfm#188]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If you have a fenced code block with a language tag, and there are backticks that aren't valid syntax for that language, syntax highlighting for the fenced code block fails to end.

This bug might be covered under #21 - I wasn't sure about the scope of that one. If so feel free to mark this as a duplicate. 

### Steps to Reproduce

![image](https://cloud.githubusercontent.com/assets/21064499/23533772/8adafb62-ff68-11e6-800a-be1ce649a860.png)

Text: https://gist.github.com/droberts-ada/2101aa83b14b0483fe86dbd01ae8bea4

**Expected behavior:** Syntax highlighting for the fenced language should stop at ```, and highlighting for markdown should resume, no matter what was inside the fenced block

**Actual behavior:** Syntax highlighting for the fenced language continues throughout the document

**Reproduces how often:** 100%

### Versions

```
$ atom --version
Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
$ apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.13
git 2.9.3
```

### Additional Information

N/A

**Comment by 50Wliu** [comment]
Yeah, this is #21.  Can't do anything about it until https://github.com/atom/first-mate/issues/83 is implemented.
