### ISSUE TITLE
Syntax highlighting is broken after any YAML code block

### ISSUE THREAD

**Issue by callumlocke** [atom/language-gfm#191]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

![image](https://cloud.githubusercontent.com/assets/250617/24291699/fbb4f912-1081-11e7-8b93-c8d965722356.png)

### Steps to Reproduce

1. Make a new file and set syntax to "GitHub Markdown"
2. Make a code block tagged as `yml` and enter any valid YAML string inside it
3. Add some more paragraphs/headings/whatever underneath the code block

**Expected behavior:** Syntax highlighting should work.

**Actual behavior:** Syntax highlighting is broken for everything after the YAML code block.

**Reproduces how often:** 100%

### Versions

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

OS X El Capitan 10.11.6 (15G1108)

**Comment by 50Wliu** [comment]
This has been fixed in the latest language-yaml version and should be fixed in Atom 1.16.0.
