### ISSUE TITLE
markdown syntax for code block does not change color

### ISSUE THREAD

**Issue by tobydrake7** [atom/language-gfm#196]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This issue was originally posted in the discussion group.
[https://discuss.atom.io/t/markdown-code-block-syntax-not-green-in-editor/41422/3](https://discuss.atom.io/t/markdown-code-block-syntax-not-green-in-editor/41422/3)

When using code block markdown syntax, the editor does not show the resulting code block as green. I have used different themes and have run in safe mode. This occurs in 1.15, but not in 1.12 or 1.14. 1.13 was not tested.

### Steps to Reproduce

1. Enter the `~~~` syntax for a code block.

~~~
code block
code block
~~~

2. The editor does not show the result in green highlighted text.

**Expected behavior:**

Text in a code block is green, or some other highlighted color (based on theme).

**Actual behavior:**

Text in a code block is the same as non code block text.

**Reproduces how often:**

100% in atom 1.15

### Versions
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

Red Hat Enterprise Linux 7.3

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

**Comment by rsese** [comment]
I was able to reproduce as well on Ubuntu 16.04 - so it does loo like the behavior changed though it's not super clear why (e.g. it doesn't seem like an intentional change).
