### ISSUE TITLE
wrong syntax highlighted for java code block.

### ISSUE THREAD

**Issue by iDragonfly2050** [atom/language-gfm#208]
### Prerequisites

-   [x] Put an X between the brackets on this line if you have done all of the following:
    -   Reproduced the problem in Safe Mode: <http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    -   Followed all applicable steps in the debugging guide: <http://flight-manual.atom.io/hacking-atom/sections/debugging/>
    -   Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    -   Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    -   Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

wrong syntax highlighted for java code block.

### Steps to Reproduce

1.  input java code block:

```java
A[] a = new A[4];
A[] b = {new A(), new A(), new A()};
A c = new A[]{new A(), new A()};
```

**Expected behavior:** hard to say.

**Actual behavior:**
![tim 20170521162947](https://cloud.githubusercontent.com/assets/16486215/26282352/e38a29c2-3e42-11e7-85c0-96de815d13c4.png)

**Reproduces how often:** Always.

### Versions

Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
language-gfm : 0.88.1

**Comment by 50Wliu** [comment]
Please reopen this on the atom/language-java repository.
