### ISSUE TITLE
Parentheses included in link scope

### ISSUE THREAD

**Issue by Aerijo** [atom/language-gfm#218]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Link scope (`markup.underline.link`) is incorrectly applied to the enclosing parentheses (not part of the link) when of the form
```gfm
[!label](link)
```
or any variant that is covered by this package.

### Steps to Reproduce

1. Paste `[!label](link)` into .gfm file.

### Additional Information

This behaviour also contradicts that of atom's `language-hyperlink`, which also picks up links this one misses (eg. in tables, which would be a separate issue).

The relevant lines that need adjusting include these ones, but others can be found by searching for `markup.underline.link`.

https://github.com/atom/language-gfm/blob/76ddd7e2fd0d6d4e897fb1394f0f3a1ca572b523/grammars/gfm.cson#L1119-L1134

Regex (modified to work): https://regex101.com/r/3S0YE7/2
^-- this shows capture group 4 is the culprit

I could make a pull request myself if necessary.

**Comment by 50Wliu** [comment]
> I could make a pull request myself if necessary.

That would definitely be appreciated.

**Comment by 50Wliu** [comment]
Fixed by #219.
