### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by stevelinus** [atom/language-gfm#237]
You have the core package "language-gfm" installed as a community package. See https://github.com/atom/atom/blob/master/packages/dalek/README.md for how this causes problems and instructions on how to correct the situation.
```
<unknown> (<embedded>:11:176366)
Generator.next (null:null:null)
step (<embedded>:11:176202)
<unknown> (null:null:null)
process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by rsese** [comment]
Thank you for the report!

The readme linked in the report gives you instructions on the steps you need to take to get rid off this deprecation https://github.com/atom/dalek#i-got-a-warning-what-do-i-do
