### ISSUE TITLE
Highlighting fails after underscore in link url

### ISSUE THREAD

**Issue by balupton** [atom/language-gfm#42]
Could be related to #39

``` markdown
[![PayPayl donate button](http://img.shields.io/paypal/donate.png?color=yellow)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=QB8GQPZAH84N6 "Donate once-off to this project using Paypal")
```

Will break highlighting for everything after it:

https://www.dropbox.com/s/zozxl6cqixtdtsg/Screenshot%202014-08-14%2016.54.27.png

Environment:
- Language Gfm 0.46.0
- Atom v0.121.0
- React editor enabled
- OS: OSX 10.9.4

**Comment by jerone** [comment]
I'm having an issue that's somewhat similar. When adding an url as text containing an underscore everything after it is interpreted as italic: 
![gfm](https://cloud.githubusercontent.com/assets/55841/11425424/29f30724-9455-11e5-9e57-e21f93fcc344.png)

On GitHub the underscore within an url _isn't_ interpreted as italic (see [here](https://github.com/jerone/UserScripts/tree/master/Github_Comment_Enhancer#test-cases)).

When changing the code to an link it does work correct: `[https://github.com/jerone/UserScripts/wiki/_new](https://github.com/jerone/UserScripts/wiki/_new)`.

Is this an intended difference between GitHub and this package?
