### ISSUE TITLE
Unrecognized #

### ISSUE THREAD

**Issue by bobrocke** [atom/language-gfm#58]
language-gfm does not recognize `#` or `##`, etc as headings and applies no classes beyond `.source` and `.gfm`.

**Comment by jonathandelgado** [comment]
+1 for no spaces required on headers

**Comment by jonathandelgado** [comment]
@kevinsawicki would you be open to a PR on this?

**Comment by kevinsawicki** [comment]
> would you be open to a PR on this?

I would worry about a case like this paragraph:

```
The blah blah blah issue was fixed in 
#3 and upgrading should resolve it.
```

If the space was optional, the entire second line would be marked as a heading when the intent was to have a hard wrapped line that happens to start with an issue reference number `#`.

**Comment by 50Wliu** [comment]
I've hit this too.  While Github's comments don't seem to render no-space headers, any .md file does (first example I could find given that I've changed most of my repositories to use the extra space: [raw](https://raw.githubusercontent.com/50DKP/FF2/development/README.md) --> [rendered](https://github.com/50DKP/FF2/blob/development/README.md)).

**Comment by kevinsawicki** [comment]
>  While Github's comments don't seem to render no-space headers, any .md file does

Great insight, then it should be changed in this package. I didn't realize this was one of the differences between comment and file parsing on the site.

@jonathandelgado were you interested in opening a PR for this?

**Comment by jonathandelgado** [comment]
@kevinsawicki Yeah, I'll get it done either tonight or tomorrow.

Thanks for the fast reply!
