### ISSUE TITLE
Add font selection to specific package

### ISSUE THREAD

**Issue by nylki** [atom/language-gfm#69]
If it's possible, I'd like to be able to specify a different font when working with markdown files (for example a serif font).
Is this in the scope of *language-gfm* or would that be a more general part of atom (for all packages' settings)?

**Comment by lee-dohm** [comment]
I would think this would be a general Atom issue, since this would potentially affect rendering and font metrics calculations and such.

**Comment by braver** [comment]
You can already do that! The current grammar is set in a data-attribute and you can style that

```
atom-text-editor[data-grammar="source gfm"],
atom-text-editor[data-grammar="source gfm"]::shadow {
    font-family: Courier;
}
```

Seems to work fine. I tried a bunch of different fonts as my default and it picks up on the different dimensions of Courier just fine each time I switch to a markdown file or switch syntaxes. As long as you pick monospaced fonts that are installed on the system you're fine.

The challenge is mostly in defining fonts that are available on every platform. I wouldn't be able to say what choices you have for a serif monospace font on Linux for instance. 

It's possible to serve fonts from a syntax-theme package with `@font-face`, but that wrecks the measurements. Chromium postpones loading the font so Atom won't know the dimensions in time. I kinda fixed that in my [fonts package](https://github.com/braver/fonts/issues/2) but it's messy.

**Comment by nylki** [comment]
> "The challenge is mostly in defining fonts that are available on every platform. I wouldn't be able to say what choices you have for a serif monospace font on Linux for instance. "
@braver 
That would be an issue if a package owner would make a decision for specific fonts in certain situations (eg. in a theme), but as a setting thats set by the user, just like the main font selection/text input field, I don't see a problem here if the default is *use the main font*.
Btw. thx for the code snippet, that works fine!

**Comment by braver** [comment]
Oh right, sure. So what you're proposing is a per-language font-name setting? That might be beyond the scope of Atom core, or a language-grammar, but definitely doable in a package.

Another related thing that popped up in my mind is that a number of fonts have the same measurements. For example, there are a number of variations of Bitstream Vera that are metrically compatible, like the serif [Verily](http://www.fontsquirrel.com/fonts/Verily-Serif-Mono). Liberation Mono (sans) matches with Courier (serif), etc. There are a number of other combinations out there that you can safely mix within the same document (e.g. serif headings).

**Comment by damieng** [comment]
You can override the font on a per-language basis in your styles.less rule by using this syntax;

```less
atom-text-editor::shadow .coffee {
  font-family: Consolas;
}
```

We have no plans to provide a UI for configuring font-settings on a per-language basis.
