### ISSUE TITLE
Underscores in HTML attributes parsed as markdown open/close italics.

### ISSUE THREAD

**Issue by davepeck** [atom/language-gfm#71]
For example, try writing `<a target="_blank">Hello</a>` in a `markdown` file in the `atom` editor and notice how everything after the `_` is italicized.

![Example screen shot](https://cloud.githubusercontent.com/assets/53165/5769823/e393576a-9cd5-11e4-9266-8321ca0f3449.png)

**Comment by 50Wliu** [comment]
Duplicate of #44.

**Comment by davepeck** [comment]
Not sure how this is a duplicate of #44 but I don't know the code, so okay! :-)
