### ISSUE TITLE
Highlights CSS Color Names - Should Not

### ISSUE THREAD

**Issue by bobrocke** [atom/language-gfm#72]
Here's what that looks like:

![www br dev - atom](https://cloud.githubusercontent.com/assets/2962426/5786809/6c0eefb2-9db9-11e4-8220-3f783d94fff7.jpg)

**Comment by lee-dohm** [comment]
I can't reproduce this on Atom v0.175.0-60970d6 on Mac OS X 10.10.1. Are you sure you're not running something like the [atom-color-highlight package](https://atom.io/packages/atom-color-highlight)? Can you duplicate this in Safe Mode?

**Comment by bobrocke** [comment]
Duh. Of course I'm using atom-color-highlight. And of course it's the problem. I'll open an issue over there.

Sorry for wasting your time.
