### ISSUE TITLE
Should not recognize italic in code block.

### ISSUE THREAD

**Issue by arielyang** [atom/language-gfm#76]
line 176, the code style is interrupted by the asterisk.

![screen shot 2015-02-04 at 23 25 22](https://cloud.githubusercontent.com/assets/212329/6043142/26497b6c-acc5-11e4-82da-fba1cd887159.png)

**Comment by arielyang** [comment]
Sorry. line 176 is

- (BOOL)application:(UIApplication *) application didFinishLaunchingWithOptions:(NSDictionary *

**Comment by arielyang** [comment]
Sorry. line 176 is

\- (BOOL)application:(UIApplication *) application didFinishLaunchingWithOptions:(NSDictionary *

**Comment by 50Wliu** [comment]
Duplicate of #44.
