### ISSUE TITLE
markdown miss-hightlight "bash" when there's the word "until"

### ISSUE THREAD

**Issue by izuzak** [atom/language-gfm#78]
_From @bric3 on February 21, 2015 14:39_

I was writing a simple git documentation for some colleagues, with bash hightlighted snippet, but Atom miss-highlight if there's the `until` word and only with the bash style.

`````` md
    ```bash
    git log --since="1 week ago" --until="yesterday"
    ```
``````

Changing the word a little (adding/removing a letter) highlighting is correct.

See : 

Incorrect :
![screenshot 2015-02-21 at 15 35 06](https://cloud.githubusercontent.com/assets/803621/6314442/5a0a32b2-b9df-11e4-9272-39f067968a62.png)

Correct (but changing one letter of the `until` letter):
![screenshot 2015-02-21 at 15 35 32](https://cloud.githubusercontent.com/assets/803621/6314444/72d286e6-b9df-11e4-92a0-8947549f1894.png)

---

**OS** : OSX 10.10.2 Yosemite
**Atom** : 0.182.0

_Copied from original issue: atom/atom#5664_

**Comment by bric3** [comment]
Actually the issue seem to be present for other bash keywords as well like `for`, `in`, etc.

**Comment by leipert** [comment]
@izuzak Isn't this a bug for [atom/language-shellscript](https://github.com/atom/language-shellscript)?

The markdown package just utilizes language-shellscript package, as can be seen [here](https://github.com/atom/language-gfm/blob/20b51131fa2b87ebaac8cec496fac2e776008d8c/grammars/gfm.cson#L421-L437)

**Comment by izuzak** [comment]
@leipert Thanks for taking a look -- I think you're right. I probably moved it here back then based on the description, and didn't really look into causes. 

If you'd like to open a new issue on the shellscript language's repository and explain why this is an issue with that package and not this one, I'd be happy to close this. Appreciate the help with triaging issues :sparkles:

**Comment by NathanRSmith** [comment]
I'm am seeing this as well. Thanks for looking into it.

**Comment by bric3** [comment]
Any update on this ?

**Comment by bric3** [comment]
How does gfm language work, can't it just pass the enclosed section to language-shellscipt ?

**Comment by 50Wliu** [comment]
No, it can't.  It's entirely regex-based.

This is on my list to fix.

**Comment by bric3** [comment]
Hi @50Wliu Thanks for the feedback !

I'm looking forward the fix ;)

**Comment by bric3** [comment]
This one can be closed maybe? As atom/language-shellscript#52 has been fixed by atom/language-shellscript#65.

Thanks again @50Wliu

**Comment by 50Wliu** [comment]
Thanks for reminding me @bric3!  I don't think your `select` example will be fixed by this, but the until one definitely has, and should be fixed in either Atom 1.14 or 1.15.

**Comment by bric3** [comment]
ah yes forgot that xml tool.

Should I create another issue for that one ?

**Comment by bric3** [comment]
@50Wliu Do you think the languages-gfm module culd be improved to pass only the relavant part toother langauge modules like proposed here ?

> Actually while the language-shellscript is badly parsing the snippet, why do the language-gfm passes the rest of the file and not just the snippet between ```.

**Comment by 50Wliu** [comment]
@bric3 the more general "we don't stop highlighting after we reach the ```" bug is being tracked at atom/first-mate#83.  Once that's fixed, then yes we will definitely start making language-gfm stop at the ```.

**Comment by bric3** [comment]
@50Wliu Great thanks for the link, I didn't find that one before !
