### ISSUE TITLE
Escaped characters not escaped

### ISSUE THREAD

**Issue by tasmo** [atom/language-gfm#79]
Backslash does not escape characters.
---
Atom interprets an with an backslash escaped underline character as start of an italic sequence. The same behaviour is happening with `*`s. 

Like in the [Markdown definition](http://daringfireball.net/projects/markdown/syntax#backslash) is written:
> Markdown allows you to use backslash escapes to generate literal
characters which would otherwise have special meaning in Markdown’s
formatting syntax.

**Comment by kevinsawicki** [comment]
Thanks so much for reporting this, it will be fixed in the next Atom release, 0.187

**Comment by tasmo** [comment]
Wow, that was quick. Thank you!
