### ISSUE TITLE
Unexpected italic style in github.com diff views

### ISSUE THREAD

**Issue by IonicaBizau** [atom/language-gfm#84]
If in the markdown code there is a `*`, everything after that character will have italic style.
I saw this recently in the GitHub diffs (e.g. [this one](https://github.com/github/git-lfs/commit/d8f780329b64e789553bc8ccccfb993ebc430325)):

![screenshot from 2015-04-09 13 56 03](https://cloud.githubusercontent.com/assets/2864371/7065956/19a9a52a-dec6-11e4-8201-9fe89f2ff9d5.png)
![screenshot from 2015-04-09 14 00 08](https://cloud.githubusercontent.com/assets/2864371/7065957/19abe218-dec6-11e4-8365-1953a6cefecf.png)

**Comment by mnquintana** [comment]
Have you seen this in Atom, or just github.com? Unfortunately this is the repo for Atom's GitHub Flavored Markdown syntax support and not github.com's – for the latter, the best option is probably to [contact GitHub support.](https://github.com/contact)

**Comment by izuzak** [comment]
@mnquintana The same problem is present in Atom as well. Also, Atom's gfm grammar is used in GitHub (through Linguist) -- check out https://github.com/github/linguist/tree/master/vendor/grammars and find the language-gfm grammar.

**Comment by IonicaBizau** [comment]
@mnquintana 
> for the latter, the best option is probably to contact GitHub support.

That's why I'm here. :smile:

**Comment by mnquintana** [comment]
@izuzak Whoops, sorry! I thought linguist maintained its own syntax support. Never mind :grin:

**Comment by IonicaBizau** [comment]
@izuzak How to reproduce this in Atom? I see there is a package named *Git Diff*, but it shows *No diffs in file* even the file was modified and has non-committed changes.

![image](https://cloud.githubusercontent.com/assets/2864371/7157526/2ebc5efa-e379-11e4-9348-8db1a3fb8d29.png)

The markdown preview works fine, but I think that is created by another package.

**Comment by izuzak** [comment]
@IonicaBizau Not sure why that's happening. Can you report a separate issue on the https://github.com/atom/git-diff package, with detailed steps to reproduce and output from Git which confirms that there is a diff in the project?

As for reproducing this issue in Atom, here's what I did: copy pasted the text from [the file](https://raw.githubusercontent.com/github/git-lfs/d8f780329b64e789553bc8ccccfb993ebc430325/README.md) into a new Atom tab and changed the language of the tab to Markdown (using the [Grammar selector](https://github.com/atom/grammar-selector)).

![screen shot 2015-04-15 at 13 21 42](https://cloud.githubusercontent.com/assets/38924/7157708/643d96ae-e372-11e4-9efa-a9c1044a1dde.png)

**Comment by IonicaBizau** [comment]
@izuzak Thanks! I see that when using `**foo` everything after that is bold (until it meets the closing `**`).

> Can you report a separate issue on the https://github.com/atom/git-diff package, with detailed steps to reproduce and output from Git which confirms that there is a diff in the project?

After restarting Atom, I cannot reproduce that anymore. However, if it happens again I will report it.

**Comment by IonicaBizau** [comment]
@izuzak To solve this issue, I think I have to edit [`grammars/gfm.cson`](https://github.com/atom/language-gfm/blob/34b0cb79626c5fba0968e9b49c93c0ba9ba8deda/grammars/gfm.cson#L17-L46). Where is this package downloaded when Atom is installed? 

Also, how can I reload the package in Atom (to test if the issue was fixed)?

**Comment by izuzak** [comment]
@IonicaBizau You should follow the workflow explained [here](https://github.com/atom/atom/blob/master/docs/contributing-to-packages.md) to clone the package locally and link it into Atom in development mode.

**Comment by IonicaBizau** [comment]
@izuzak Nice! I expected something like that. :smile:  I created a PR (#89) with what I have done.

**Comment by 50Wliu** [comment]
I'm going to close this in favor of #44 in order to keep discussion unified.
