### ISSUE TITLE
How to run the tests?

### ISSUE THREAD

**Issue by IonicaBizau** [atom/language-gfm#88]
It seems there is no script associated with `npm test`. However I see the `spec` directory which contains tests.

How to run these tests?
Probably `npm test` should be fixed as well (I can do that).

**Comment by thomasjo** [comment]
Just execute `apm test` from the repository root.

**Comment by IonicaBizau** [comment]
@thomasjo Thanks! :+1: Should I add it in the `package.json` (`scripts.test`)? If so, I will make a PR.

**Comment by thomasjo** [comment]
I don't understand what you mean? The specs live in `spec/` and there's no need to update `package.json` in order to run specs. Feel free to explain what you think needs to be changed if I didn't just clear it up.

**Comment by IonicaBizau** [comment]
Running `npm test` outputs an error:

```sh
$ npm test

> language-gfm@0.68.0 test /home/.../language-gfm
> echo "Error: no test specified"

Error: no test specified
```

We could fix this by adding the following snippet in `package.json`:

```json
{
   "scripts": {
      "test": "apm test"
   }
}
```

Then, running `npm test` will work fine (actually will run the provided command: `apm test`).

**Comment by thomasjo** [comment]
But you aren't supposed to run `npm test`, you have to run `apm test`.

**Comment by IonicaBizau** [comment]
I see. Thanks a lot!

**Comment by thomasjo** [comment]
> I see. Thanks a lot!

No problem! :bow:
