### ISSUE TITLE
missing sql block syntax highlight

### ISSUE THREAD

**Issue by trydofor** [atom/language-gfm#98]
Ubuntu 14.04.2 LTS
`sudo add-apt-repository ppa:webupd8team/atom`
$atom -v
0.198.0

    ``` sql
    -- sql's highlight is missing
    select * from a;
    ```

    ``` java
    // java is ok
    package test;
    ```

 ``` SQL
-- sql's highlight is missing
select * from a;
```

``` java
 // java is ok
 package test;
```

**Comment by jacobbednarz** [comment]
@trydofor do you mind pulling #99 locally and confirm it works for you?

**Comment by trydofor** [comment]
@jacobbednarz I installed it by apt-get, so I can not confirm it.
after reading the diffs of #99 , it believe it works fine.
